### ISSUE TITLE
.env file is missing

### ISSUE THREAD

**Issue by Samuele1no** [dariowskii/open_gpt_client#2]
Inside the pubspec.yaml assets list there is the ".env" file but this is not present in the project.
Is it missing (and we need to create it from scratch) or generated by some command?

**Comment by dariowskii** [comment]
Hi @Samuele1no!

You need to create a ".env" file (unnamed) in the root of the project in order to run the project.

I'm creating a guide to contribute to the project where I explain everything in detail that I'll be posting in the master branch shortly.
