### ISSUE TITLE
Error on length of generated password

### ISSUE THREAD

**Issue by Samuele1no** [dariowskii/open_gpt_client#3]
When I use generate password method, it gives me a password (not correct) and when I go to "conferma" and then "avanti" the app goes on error. The length of the key is 33, as it shows the attached screenshot.

<img width="1018" alt="Screenshot 2023-04-15 alle 20 11 25" src="https://user-images.githubusercontent.com/72403261/232246283-f629d142-1d01-4728-971e-cecc0a17beab.png">

**Comment by dariowskii** [comment]
Hi @Samuele1no!

I tested by writing this unit test, generating 100,000 passwords and passing the test successfully. 

![test_correct_length](https://user-images.githubusercontent.com/62183044/232339706-f3f6c9c8-fa9b-4231-8af7-488154e52ccf.png)

I will definitely implement a character limit to the textfield and add checks before generating the encrypter, but I can't replicate the error you mentioned. 

Can you provide more information?

Thank you!

P.S. I put the unit test in the repo (or you can copy it), I kindly ask you to try to run it on your machine and share feedback in case it misbehaves.

```dart
test('password generator correct length', () {
  const configuration = PasswordGeneratorConfiguration(
    length: 32,
  );
  final generator = PasswordGenerator.fromConfig(configuration: configuration);
  const numOfGeneratedPasswords = 100000;
  for (var i = 0; i < numOfGeneratedPasswords; i++) {
    final password = generator.generate();
    expect(password.length, 32);
  }
});
```

**Comment by dariowskii** [comment]
Hi @Samuele1no!

After several tests I caught the bug you were talking about!

The problem arises from the fact that some special characters occupy 2 bytes when encoded in `utf8` generating `utf8.encode(key).length == 33`.

The bug will be fixed in the next release!

Thank you!
