### ISSUE TITLE
Release 0.1.0 doesn't work on M1 macos

### ISSUE THREAD

**Issue by mad-mikey** [dariowskii/open_gpt_client#4]
**Describe the bug**
Hi,
I try to download the dmg for maos, but I have a M1 chipset and when I try to install it, macos tell me that is a malicious software and it can't open it.

Thank you for your work. 
The application seems very good

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version 13.4 (22F66)

**Comment by dariowskii** [comment]
Hi @mad-mikey,

You can try right-clicking to open the menu, then clicking "Open". You will be asked if you want to trust the author and still open the application. From then on, he shouldn't ask you anything anymore.

I kindly ask you to give me feedback in order to close the issue.

**Comment by mad-mikey** [comment]
Hi @dariowskii,
thank you for your answer, something strange happen. For many times it can't open the app (always the same message), now it seems to works. I don't have actually the message to trust the author, but it seems to work.

Thank you very much

**Comment by dariowskii** [comment]
Well, in the end the important thing is that you can use it! 😁

If you encounter new errors again, please let me know by opening a new issue.

Thanks for your collaboration!
